### ISSUE TITLE
Image GET generates 404

### ISSUE THREAD

**Issue by earcanal** [expfactory-experiments/local-global-shape#1]
# To replicate

`python3 -m http.server 9999`

# Symptom

```
GET http://localhost:9999/%3Cdiv%20class%20=%20centerbox%3E%3Cimg%20src%20=%20%22images/black_triangleoftriangles.png%22%3C/img%3E%3C/div%3E 404 (File not found)
...
```

# Probable cause

I suspect that [poldrack-categorize](https://github.com/expfactory-experiments/local-global-shape/blob/master/js/jspsych/poldrack_plugins/jspsych-poldrack-categorize.js) modifies the `src` attribute of an `Image` object, and there's a registered callback that runs when this attribute changes.  This only generates warnings in the version of jsPsych used in this experiment.  However, [this will prevent the experiment from running in more recent versions](https://github.com/jspsych/jsPsych/blob/master/jspsych.js#L2183).

I've noticed these 404s for a while, but I only triggered this bug when testing this task with jsPsych 6.0.4.

**Comment by vsoch** [comment]
I've seen this bug on a lot of the jspsych experiments, and (I might be wrong) but I thought it was related to a get of a function, or something similar. Do you have a suggestion for a fix?

**Comment by earcanal** [comment]
I'm working on a fix.  You can see `src` being modified in the plugin which supports my causal hypothesis!  I think the trick is to modify the DOM without modifying this attribute.

**Comment by vsoch** [comment]
Ouch, I wonder if @IanEisenberg has comment on this? I think he is traveling or otherwise busy, because he has been largely silent when we ping him. Hey Ian! :)

**Comment by earcanal** [comment]
Hmmm.  Not at the bottom of it yet, but `module.preloadImages` is being called twice.  [Once with a valid list of images](https://github.com/expfactory-experiments/local-global-shape/blob/master/experiment.js#L121), but then again with a list of the 96 HTML strings which are the stimuli associated with `test_block`.

**Comment by earcanal** [comment]
I've submitted a PR for this which sets `auto_preload: false`.  It will need applying to most experiments to make those warnings go away, and to prevent them being elevated to errors in more recent versions of jsPsych.

**Comment by vsoch** [comment]
okay @earcanal if you want to test if this is fixed in the container:

```
docker run -p 80:80 expfactory/local-global-shape start
```
